---
title: "SILAM data normality and homoscedasticity check"
output: html_document
date: "2023-10-18"

The purpose of this script is to check the normality and homoscedasticity of the data 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages

```{r}
# Load necessary libraries
library(ggplot2)
library(dplyr)
```


## Load files

```{r}
df = read.csv('../output_7/peptide_level_filtered.csv')

# exclude 0 
df <- df %>%
  filter(value != 0)
```


## Visually check the normality via histogram

You can also embed plots, for example:

```{r, echo=FALSE}
# Create histograms grouped by 'Day' and 'Oxygen'
ggplot(df, aes(x = log(value))) +
  geom_histogram(binwidth = 0.5, fill = "blue") +  # Adjust 'binwidth' as needed
  facet_grid(Day ~ Oxygen, scales = "free") +
  labs(title = "Histograms of Protein Expression by Day and Oxygen",
       x = "Scaled Value",
       y = "Frequency")
```

## QQ plots

```{r}

# Create Q-Q plots grouped by 'Day' and 'Oxygen'
ggplot(df, aes(sample = log(value))) +
  geom_qq() +
  facet_grid(Day ~ Oxygen) +
  labs(title = "Q-Q Plots of Protein Expression by Day and Oxygen")

```


## Statistics to check the normality 

```{r}

# Perform Shapiro-Wilk test for normality grouped by 'Day' and 'Oxygen'
sample_size <- min(1000, nrow(df)) ## downsample data 
sampled_dataset <- df %>%
  sample_n(size = sample_size)

shapiro_test_results <- sampled_dataset %>%
  group_by(Day, Oxygen) %>%
  summarise(p_value = shapiro.test(log(value))$p.value)

# View the results
print(shapiro_test_results)

```



## Data homoscedasticity

```{r echo}
# Create scatterplots of scaled_value vs. Day, colored by Oxygen
ggplot(df, aes(x = Day, y = log(scaled_value), color = Oxygen)) +
  geom_point() +
  labs(title = "Scatterplot of Protein Expression vs. Day (Colored by Oxygen)",
       x = "Day",
       y = "Scaled Value")


```

```{r}
# Perform statistical tests for homoscedasticity by fitting linear models

df <- df %>%
  filter(scaled_value != 0)
homoscedasticity_test_results <- df %>%
  group_by(Oxygen) %>%
  do(model_fit = lm(log(scaled_value) ~ Day, data = .)) %>%
  summarise(
    p_value = summary(model_fit)$fstatistic[1],
    df1 = summary(model_fit)$fstatistic[2],
    df2 = summary(model_fit)$fstatistic[3]
  )

print(homoscedasticity_test_results)

```

